# Generated by Django 3.1.3 on 2020-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyChecker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyrate',
            old_name='uah_amount',
            new_name='uah_rate',
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(),
        ),
    ]
